version: "3"
services:

  mongo-crud-api:
    image: mongo:latest
    restart: always
    container_name: mongo-crud-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: luis
      MONGO_INITDB_ROOT_PASSWORD: luissoy
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-crud-api-network

  mongo-express-crud-api:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express-crud-api
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: luis
      ME_CONFIG_BASICAUTH_PASSWORD: luissoy
      ME_CONFIG_MONGODB_ADMINUSERNAME: luis
      ME_CONFIG_MONGODB_ADMINPASSWORD: luissoy
      ME_CONFIG_MONGODB_SERVER: mongo-crud-api
      ME_CONFIG_MONGODB_URL: mongodb://mongo-crud-api:27017
    depends_on:
      - mongo-crud-api
    networks:
      - mongo-crud-api-network

networks:
  mongo-crud-api-network:
    name: mongo-crud-api-network
    driver: bridge